[package]
name = "tpt-wasm-validate"
description = "WebAssembly validation pass for tpt-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tpt-wasm-types.workspace = true
tpt-wasm-format.workspace = true
tpt-wasm-decode.workspace = true
