[package]
name = "tpt-wasm-spec"
description = "Official WebAssembly spec test harness for tpt-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tpt-wasm-decode.workspace = true
tpt-wasm-validate.workspace = true
