[package]
name = "tpt-wasm-runtime"
description = "WebAssembly runtime (Store, Instance, Linker, Engine) for tpt-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tpt-wasm-format.workspace = true
tpt-wasm-decode.workspace = true
tpt-wasm-types.workspace = true
tpt-wasm-validate.workspace = true
tpt-wasm-micro.workspace = true
